"""Public interface for the DroneDream PX4 parameter registry."""

from app.parameters.catalog import (
    CATALOG_SOURCE,
    CATALOG_SOURCE_URL,
    CATALOG_VERSION,
    CATALOG_VERSION_ALIASES,
    GROUPS,
    SUPPORTED_AIRFRAME_FAMILIES,
    SUPPORTED_PX4_VERSIONS,
    SUPPORTED_TRIAL_METRICS,
    SUPPORTED_VEHICLE_TYPES,
    TUNING_PRESETS,
    WORKFLOW_PRECONDITIONS,
    catalog_payload,
    classify_airframe,
    get_parameter,
    list_parameters,
    list_presets,
    normalize_px4_version,
    normalize_vehicle_type,
    preset_payload,
    resolve_catalog_version,
)
from app.parameters.models import ParameterSelection, SelectionValidationResult, ValidationIssue
from app.parameters.validation import (
    ParameterValueValidationError,
    validate_parameter_values,
    validate_search_selections,
)

__all__ = [
    "CATALOG_SOURCE",
    "CATALOG_SOURCE_URL",
    "CATALOG_VERSION",
    "CATALOG_VERSION_ALIASES",
    "GROUPS",
    "SUPPORTED_AIRFRAME_FAMILIES",
    "SUPPORTED_PX4_VERSIONS",
    "SUPPORTED_TRIAL_METRICS",
    "SUPPORTED_VEHICLE_TYPES",
    "TUNING_PRESETS",
    "WORKFLOW_PRECONDITIONS",
    "ParameterSelection",
    "ParameterValueValidationError",
    "SelectionValidationResult",
    "ValidationIssue",
    "catalog_payload",
    "classify_airframe",
    "get_parameter",
    "list_presets",
    "list_parameters",
    "normalize_px4_version",
    "normalize_vehicle_type",
    "preset_payload",
    "resolve_catalog_version",
    "validate_parameter_values",
    "validate_search_selections",
]
