// Generated by scripts/build-brand-assets.py. Do not edit.
export const BRAND_EDITION_IDS = ["universal", "sim", "lab", "field"] as const;
export type BrandEditionId = (typeof BRAND_EDITION_IDS)[number];
export const EDITION_BRAND_TOKENS = {
  "universal": {
    "productName": "DroneDream",
    "editionLabel": null,
    "gradientStops": [
      "#FF5574",
      "#6A4CFF",
      "#E657D1"
    ],
    "lightSurface": "#F8F5FF",
    "darkSurface": "#171225"
  },
  "sim": {
    "productName": "DroneDream · SIM",
    "editionLabel": "SIM",
    "gradientStops": [
      "#00D9FF",
      "#2671FF",
      "#744CFF"
    ],
    "lightSurface": "#F1FAFF",
    "darkSurface": "#071B31"
  },
  "lab": {
    "productName": "DroneDream · LAB",
    "editionLabel": "LAB",
    "gradientStops": [
      "#A7E84A",
      "#20C77A",
      "#087E69"
    ],
    "lightSurface": "#F3FCEF",
    "darkSurface": "#092019"
  },
  "field": {
    "productName": "DroneDream · FIELD",
    "editionLabel": "FIELD",
    "gradientStops": [
      "#FFC247",
      "#FF754B",
      "#D746A5"
    ],
    "lightSurface": "#FFF8EF",
    "darkSurface": "#28140D"
  }
} as const;
export const BRAND_PRESENTATION_ONLY = true as const;
export const BRAND_GRANTS_HARDWARE_AUTHORITY = false as const;
