[Journal]
Storage=persistent
Compress=yes
Seal=yes
SystemMaxUse=512M
RuntimeMaxUse=256M
SystemKeepFree=20G
RuntimeKeepFree=128M
MaxRetentionSec=14day
MaxFileSec=1day
RateLimitIntervalSec=30s
RateLimitBurst=10000
ForwardToSyslog=no
