; DroneDream-specific installer copy. Every visible custom string has one value
; per supported language so the selected installer language is never mixed.

LangString DD_RuntimeBusy ${LANG_ENGLISH} "DroneDreamRuntime is busy, or another installer owns maintenance. Wait for or cancel that task, then try again."
LangString DD_RuntimeBusy ${LANG_SIMPCHINESE} "DroneDreamRuntime 正在运行，或另一个安装器正在维护它。请等待任务完成或取消任务后重试。"
LangString DD_RuntimePendingUpdate ${LANG_ENGLISH} "Runtime setup is waiting to continue. Open DroneDream to finish or cancel it before updating."
LangString DD_RuntimePendingUpdate ${LANG_SIMPCHINESE} "Runtime 安装正在等待续传。请先打开 DroneDream 完成或取消安装，再进行升级。"
LangString DD_RuntimeIsolationFailed ${LANG_ENGLISH} "Unable to establish safe Runtime update isolation. Setup has stopped."
LangString DD_RuntimeIsolationFailed ${LANG_SIMPCHINESE} "无法建立安全的 Runtime 升级隔离，安装已停止。"
LangString DD_DowngradeBlocked ${LANG_ENGLISH} "A newer DroneDream version is already installed. This older installer will close without changing the installed application."
LangString DD_DowngradeBlocked ${LANG_SIMPCHINESE} "电脑上已安装更新版本的 DroneDream。这个旧安装程序将直接关闭，不会更改当前安装。"
LangString DD_ShortcutConflict ${LANG_ENGLISH} "The requested shortcut name is already owned by another DroneDream installation. Setup preserved the existing shortcut and did not replace it."
LangString DD_ShortcutConflict ${LANG_SIMPCHINESE} "所需的快捷方式名称已属于另一个 DroneDream 安装。安装程序已保留现有快捷方式，未进行覆盖。"

LangString DD_ModeHeader ${LANG_ENGLISH} "Choose what to install"
LangString DD_ModeHeader ${LANG_SIMPCHINESE} "选择安装内容"
LangString DD_ModeRequirements ${LANG_ENGLISH} "PX4/Gazebo downloads up to 8 GiB, uses about 24 GiB after installation, and requires at least 52 GiB free."
LangString DD_ModeRequirements ${LANG_SIMPCHINESE} "PX4/Gazebo 下载最多约 8 GiB，安装后约占 24 GiB，并要求至少 52 GiB 可用空间。"
LangString DD_InstallAll ${LANG_ENGLISH} "Install everything (recommended)"
LangString DD_InstallAll ${LANG_SIMPCHINESE} "安装全部（推荐）"
LangString DD_RecommendedTarget ${LANG_ENGLISH} "Recommended Runtime location: $DroneDreamPlanTarget"
LangString DD_RecommendedTarget ${LANG_SIMPCHINESE} "推荐的 Runtime 位置：$DroneDreamPlanTarget"
LangString DD_NoRecommendedTarget ${LANG_ENGLISH} "No eligible Runtime drive was detected automatically."
LangString DD_NoRecommendedTarget ${LANG_SIMPCHINESE} "未能自动检测到符合条件的 Runtime 磁盘。"
LangString DD_RuntimeSetupDeferred ${LANG_ENGLISH} "Runtime setup will continue inside the desktop application."
LangString DD_RuntimeSetupDeferred ${LANG_SIMPCHINESE} "运行环境将在桌面程序中继续设置。"
LangString DD_CustomDrive ${LANG_ENGLISH} "Choose a Runtime drive"
LangString DD_CustomDrive ${LANG_SIMPCHINESE} "自定义 Runtime 磁盘"
LangString DD_CustomDriveHint ${LANG_ENGLISH} "Enter a drive such as E:. Runtime will use X:\DroneDream."
LangString DD_CustomDriveHint ${LANG_SIMPCHINESE} "输入盘符（例如 E:）；Runtime 将使用 X:\DroneDream。"
LangString DD_AppOnly ${LANG_ENGLISH} "Install the desktop application only"
LangString DD_AppOnly ${LANG_SIMPCHINESE} "仅安装桌面程序"
LangString DD_ModeNote ${LANG_ENGLISH} "Your existing Ubuntu distributions are never modified. Runtime setup starts in DroneDream after this installer finishes."
LangString DD_ModeNote ${LANG_SIMPCHINESE} "现有 Ubuntu 不会被修改。此安装器完成后，Runtime 安装将在 DroneDream 中自动开始。"
LangString DD_NoEligibleDrive ${LANG_ENGLISH} "No safe writable fixed NTFS drive with at least 52 GiB free was found. You can enter a drive manually or install only the desktop application."
LangString DD_NoEligibleDrive ${LANG_SIMPCHINESE} "未找到至少有 52 GiB 可用空间的安全、可写固定 NTFS 磁盘。你可以手动输入盘符，或仅安装桌面程序。"
LangString DD_PlannerUnavailable ${LANG_ENGLISH} "Automatic drive detection did not finish. Enter a drive manually to retry the check, or install only the desktop application."
LangString DD_PlannerUnavailable ${LANG_SIMPCHINESE} "自动磁盘检测未能完成。请手动输入盘符重试检查，或仅安装桌面程序。"
LangString DD_PlannerFailureDetails ${LANG_ENGLISH} "Automatic disk detection could not run ($DroneDreamPlanDiagnosticCode). Details were saved to $DroneDreamDiagnosticLog. Retry detection, enter a drive manually, or cancel setup."
LangString DD_PlannerFailureDetails ${LANG_SIMPCHINESE} "自动磁盘检测无法运行（$DroneDreamPlanDiagnosticCode）。详细信息已保存到 $DroneDreamDiagnosticLog。请重新检测、手动输入盘符，或取消安装。"
LangString DD_PreflightBlocked ${LANG_ENGLISH} "A Runtime location was found, but this computer did not pass every Runtime preflight check. Install the desktop application to view the detailed diagnostics."
LangString DD_PreflightBlocked ${LANG_SIMPCHINESE} "已找到 Runtime 位置，但这台电脑未通过全部 Runtime 预检。请先安装桌面程序，再查看详细诊断。"
LangString DD_InstallButton ${LANG_ENGLISH} "Install"
LangString DD_InstallButton ${LANG_SIMPCHINESE} "安装"
LangString DD_RetryDetection ${LANG_ENGLISH} "Retry detection"
LangString DD_RetryDetection ${LANG_SIMPCHINESE} "重新检测"
LangString DD_DetectionSucceeded ${LANG_ENGLISH} "Disk detection succeeded. The recommended Runtime location is $DroneDreamPlanTarget."
LangString DD_DetectionSucceeded ${LANG_SIMPCHINESE} "磁盘检测成功。推荐的 Runtime 位置是 $DroneDreamPlanTarget。"
LangString DD_CustomDriveRequired ${LANG_ENGLISH} "Enter a drive for the custom Runtime installation, for example E:."
LangString DD_CustomDriveRequired ${LANG_SIMPCHINESE} "自定义 Runtime 安装必须输入盘符，例如 E:。"
LangString DD_SelectedDriveInvalid ${LANG_ENGLISH} "The selected drive must be a safe, writable fixed NTFS drive with at least 52 GiB free."
LangString DD_SelectedDriveInvalid ${LANG_SIMPCHINESE} "所选磁盘必须是安全、可写的固定 NTFS 磁盘，并且至少有 52 GiB 可用空间。"
LangString DD_SelectedDriveProbeFailed ${LANG_ENGLISH} "The selected drive could not be checked ($DroneDreamPlanDiagnosticCode). Details were saved to $DroneDreamDiagnosticLog. Retry detection or cancel setup."
LangString DD_SelectedDriveProbeFailed ${LANG_SIMPCHINESE} "无法检查所选磁盘（$DroneDreamPlanDiagnosticCode）。详细信息已保存到 $DroneDreamDiagnosticLog。请重新检测或取消安装。"
LangString DD_AppAtRuntimeRoot ${LANG_ENGLISH} "The desktop application cannot be installed in $DroneDreamPlanTarget. Go back and choose another application folder."
LangString DD_AppAtRuntimeRoot ${LANG_SIMPCHINESE} "桌面程序不能安装到 $DroneDreamPlanTarget。请返回并选择其他桌面安装目录。"
LangString DD_AppBelowRuntimeRoot ${LANG_ENGLISH} "The desktop application cannot be installed below $DroneDreamPlanTarget. Go back and choose another application folder."
LangString DD_AppBelowRuntimeRoot ${LANG_SIMPCHINESE} "桌面程序不能安装到 $DroneDreamPlanTarget 的子目录。请返回并选择其他桌面安装目录。"
LangString DD_AppPathCheckFailed ${LANG_ENGLISH} "The desktop application path could not be validated safely. Go back and choose the default application folder, or cancel setup."
LangString DD_AppPathCheckFailed ${LANG_SIMPCHINESE} "无法安全验证桌面程序路径。请返回并选择默认的桌面安装目录，或取消安装。"

LangString DD_UpdatePending ${LANG_ENGLISH} "Runtime setup is waiting to continue. Open DroneDream to finish or cancel it before updating or reinstalling."
LangString DD_UpdatePending ${LANG_SIMPCHINESE} "Runtime 安装正在等待续传。请先打开 DroneDream 完成或取消安装，再升级或重装。"
LangString DD_UpdateBusy ${LANG_ENGLISH} "DroneDreamRuntime is busy, or another installer owns maintenance."
LangString DD_UpdateBusy ${LANG_SIMPCHINESE} "DroneDreamRuntime 正忙，或另一个安装器正在维护它。"
LangString DD_UpdateIsolationInvalid ${LANG_ENGLISH} "Unable to validate safe Runtime update isolation. The application was not replaced."
LangString DD_UpdateIsolationInvalid ${LANG_SIMPCHINESE} "无法验证安全的 Runtime 升级隔离，应用程序未被覆盖。"
LangString DD_LegacyRuntimeBusy ${LANG_ENGLISH} "DroneDreamRuntime is busy. Cancel or wait for it in DroneDream, then try again."
LangString DD_LegacyRuntimeBusy ${LANG_SIMPCHINESE} "DroneDreamRuntime 正在运行安装或维护。请先在软件中取消任务或等待完成后重试。"
LangString DD_RuntimeStateUnknown ${LANG_ENGLISH} "Unable to verify the DroneDreamRuntime operation state. Setup stopped safely."
LangString DD_RuntimeStateUnknown ${LANG_SIMPCHINESE} "无法验证 DroneDreamRuntime 状态，安装已安全停止。"
LangString DD_RuntimeRequestUnknown ${LANG_ENGLISH} "Unable to verify the pending Runtime request. Setup stopped safely."
LangString DD_RuntimeRequestUnknown ${LANG_SIMPCHINESE} "无法验证待处理的 Runtime 请求，安装已安全停止。"
LangString DD_WebViewRepair ${LANG_ENGLISH} "WebView2 registration is incomplete. Starting the official Microsoft repair."
LangString DD_WebViewRepair ${LANG_SIMPCHINESE} "WebView2 注册不完整，正在启动 Microsoft 官方修复程序。"
LangString DD_WebViewInstallFailed ${LANG_ENGLISH} "Microsoft WebView2 could not be installed (exit code $1). Restart Windows, make sure C: has at least 2 GB free, and try again."
LangString DD_WebViewInstallFailed ${LANG_SIMPCHINESE} "Microsoft WebView2 安装失败（退出代码 $1）。请重启 Windows、确保 C 盘至少有 2 GB 可用空间后重试。"
LangString DD_WebViewStillUnusable ${LANG_ENGLISH} "Microsoft WebView2 is still unusable. Restart Windows and try again; if necessary, run this installer as administrator."
LangString DD_WebViewStillUnusable ${LANG_SIMPCHINESE} "Microsoft WebView2 仍不可用。请重启 Windows 后重试；必要时以管理员身份运行本安装器。"
LangString DD_ClearRequestFailed ${LANG_ENGLISH} "Unable to clear the previous Runtime setup request."
LangString DD_ClearRequestFailed ${LANG_SIMPCHINESE} "无法清除旧的 Runtime 安装请求。"
LangString DD_SaveRequestFailed ${LANG_ENGLISH} "Unable to save the verified Runtime setup request."
LangString DD_SaveRequestFailed ${LANG_SIMPCHINESE} "无法保存已验证的 Runtime 安装请求。"
LangString DD_ReleaseIsolationFailed ${LANG_ENGLISH} "Unable to release Runtime update isolation. Setup stopped before launching DroneDream."
LangString DD_ReleaseIsolationFailed ${LANG_SIMPCHINESE} "无法解除 Runtime 升级隔离，安装已在启动 DroneDream 前停止。"

LangString DD_UninstallPending ${LANG_ENGLISH} "Runtime setup is waiting to continue. Open DroneDream to finish or cancel it before uninstalling."
LangString DD_UninstallPending ${LANG_SIMPCHINESE} "Runtime 安装正在等待续传。请先打开 DroneDream 完成或取消安装，再进行卸载。"
LangString DD_UninstallBusy ${LANG_ENGLISH} "DroneDreamRuntime is busy, or another installer owns maintenance. Uninstall has stopped."
LangString DD_UninstallBusy ${LANG_SIMPCHINESE} "DroneDreamRuntime 正忙，或另一个安装器正在维护它，卸载已停止。"
LangString DD_UninstallIsolationFailed ${LANG_ENGLISH} "Unable to establish safe Runtime uninstall isolation. Uninstall has stopped."
LangString DD_UninstallIsolationFailed ${LANG_SIMPCHINESE} "无法建立安全的 Runtime 卸载隔离，卸载已停止。"
LangString DD_UninstallLegacyBusy ${LANG_ENGLISH} "DroneDreamRuntime is busy. Cancel or wait for the operation before uninstalling the desktop application."
LangString DD_UninstallLegacyBusy ${LANG_SIMPCHINESE} "DroneDreamRuntime 正在工作。请先取消任务或等待任务完成，再卸载桌面程序。"
LangString DD_UninstallStateUnknown ${LANG_ENGLISH} "Unable to verify the Runtime state. Uninstall stopped safely."
LangString DD_UninstallStateUnknown ${LANG_SIMPCHINESE} "无法验证 Runtime 状态，卸载已安全停止。"
LangString DD_UninstallRequestUnknown ${LANG_ENGLISH} "Unable to verify the pending Runtime request. Uninstall stopped safely."
LangString DD_UninstallRequestUnknown ${LANG_SIMPCHINESE} "无法验证待处理的 Runtime 请求，卸载已安全停止。"
LangString DD_UninstallClearFailed ${LANG_ENGLISH} "Unable to clear the pending Runtime request. Uninstall stopped safely."
LangString DD_UninstallClearFailed ${LANG_SIMPCHINESE} "无法清除待处理的 Runtime 请求，卸载已安全停止。"
