FROM node:22-alpine AS build
WORKDIR /app
ARG VITE_API_BASE_URL=
ARG VITE_HOSTED_MODE=false
ARG VITE_LOCK_SIMULATOR_BACKEND=false
ARG VITE_DEFAULT_SIMULATOR_BACKEND=mock
ARG VITE_DEFAULT_OPTIMIZER_STRATEGY=gpt
ARG VITE_REQUIRE_DEMO_AUTH_TOKEN=false
ARG VITE_SERVER_OPENAI_ENABLED=false
ARG VITE_GAZEBO_VIEWER_URL=
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL VITE_HOSTED_MODE=$VITE_HOSTED_MODE VITE_LOCK_SIMULATOR_BACKEND=$VITE_LOCK_SIMULATOR_BACKEND VITE_DEFAULT_SIMULATOR_BACKEND=$VITE_DEFAULT_SIMULATOR_BACKEND VITE_DEFAULT_OPTIMIZER_STRATEGY=$VITE_DEFAULT_OPTIMIZER_STRATEGY VITE_REQUIRE_DEMO_AUTH_TOKEN=$VITE_REQUIRE_DEMO_AUTH_TOKEN VITE_SERVER_OPENAI_ENABLED=$VITE_SERVER_OPENAI_ENABLED VITE_GAZEBO_VIEWER_URL=$VITE_GAZEBO_VIEWER_URL
COPY frontend /app
RUN npm install && npm run build
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
