from __future__ import annotations

from typing import Any

from dronedream_agent_core.plugin_api import PluginDefinition

from ._helpers import hook_plugin


def _action(
    action_id: str,
    domain_id: str,
    label: str,
    description: str,
    *,
    movement: bool = False,
    payload: bool = False,
    boundary: str = "none",
    success: list[str],
    fallbacks: list[str],
    simulator: str,
    runtime: str | None = None,
    authority: str = "plan",
    input_schema: dict[str, object] | None = None,
) -> dict[str, object]:
    return {
        "schema_version": "dronedream.action-definition.v1",
        "action_id": action_id,
        "domain_id": domain_id,
        "label": label,
        "description": description,
        "movement": movement,
        "payload": payload,
        "flight_boundary": boundary,
        "input_schema": input_schema or {"type": "object", "additionalProperties": False},
        "required_success_evidence": success,
        "allowed_fallbacks": fallbacks,
        "simulator_executor": simulator,
        "runtime_executor": runtime,
        "authority": authority,
    }


def _pack(domain_id: str, actions: list[dict[str, object]]):
    def declare(**_: Any) -> dict[str, object]:
        return {"domain_id": domain_id, "actions": actions}

    return declare


def _definition(
    *,
    plugin_id: str,
    name: str,
    description: str,
    domain_id: str,
    actions: list[dict[str, object]],
    order: int,
    failure_mode: str = "fail-closed",
) -> PluginDefinition:
    return hook_plugin(
        module_name=__name__,
        plugin_id=plugin_id,
        name=name,
        description=description,
        capability_id=f"{plugin_id}.actions",
        capability_kind="action-pack",
        capability_name=name,
        capability_description=description,
        category_id="mission-domain",
        category_label="任务领域与动作",
        slot_id="mission.action-packs",
        slot_label="任务动作包",
        activation_mode="multiple",
        category_order=25,
        slot_order=10,
        plugin_order=order,
        hooks={"declare_actions": _pack(domain_id, actions)},
        default_enabled=True,
        failure_mode=failure_mode,
        swap_policy="next-mission",
        metadata={"domain_id": domain_id, "action_ids": [item["action_id"] for item in actions]},
    )


def plugin_definitions() -> list[PluginDefinition]:
    core = "core.flight"
    delivery = "delivery.custody"
    inspection = "inspection.infrastructure"
    survey = "survey.mapping"
    emergency = "emergency.response"
    maintenance = "maintenance.facility"
    return [
        _definition(
            plugin_id="actions.core-flight",
            name="核心飞行动作",
            description="保留起飞、移动、返航和降落边界，是所有任务动作包的基础。",
            domain_id=core,
            order=10,
            actions=[
                _action(
                    "none",
                    core,
                    "无载荷动作",
                    "明确表示任务不需要载荷操作。",
                    success=["no payload action required"],
                    fallbacks=["continue", "hold"],
                    simulator="sim.core.noop",
                ),
                _action(
                    "takeoff",
                    core,
                    "起飞",
                    "从已验证起飞点进入稳定悬停。",
                    boundary="takeoff",
                    success=["airborne", "stable hover"],
                    fallbacks=["land", "abort"],
                    simulator="sim.flight.takeoff",
                    runtime="native.flight.takeoff",
                    authority="control",
                ),
                _action(
                    "traverse",
                    core,
                    "通行",
                    "沿已验证路线穿越建筑或室外连接区域。",
                    movement=True,
                    success=["segment complete", "clearance maintained"],
                    fallbacks=["hold", "return", "land"],
                    simulator="sim.flight.follow-track",
                    runtime="native.flight.follow-track",
                    authority="control",
                ),
                _action(
                    "navigate",
                    core,
                    "导航",
                    "导航至合同中授权的目标节点。",
                    movement=True,
                    success=["target reached", "pose stable"],
                    fallbacks=["hold", "return", "land"],
                    simulator="sim.flight.follow-track",
                    runtime="native.flight.follow-track",
                    authority="control",
                ),
                _action(
                    "return",
                    core,
                    "返程",
                    "返回合同中冻结的返程节点。",
                    movement=True,
                    success=["return node reached"],
                    fallbacks=["hold", "land", "abort"],
                    simulator="sim.flight.follow-track",
                    runtime="native.flight.follow-track",
                    authority="control",
                ),
                _action(
                    "land",
                    core,
                    "降落",
                    "在已验证着陆区域完成受控降落。",
                    boundary="landing",
                    success=["landed", "motors safe"],
                    fallbacks=["hold", "abort"],
                    simulator="sim.flight.land",
                    runtime="native.flight.land",
                    authority="control",
                ),
            ],
        ),
        _definition(
            plugin_id="actions.delivery-custody",
            name="配送与交接动作",
            description="提供取件、身份核验、扫码和释放载荷的完整交接链。",
            domain_id=delivery,
            order=20,
            actions=[
                _action(
                    "pickup",
                    delivery,
                    "取件",
                    "验证目标包裹并完成抓取或挂载。",
                    payload=True,
                    success=["recipient or parcel verified", "payload attached"],
                    fallbacks=["hold", "return", "abort"],
                    simulator="sim.payload.pickup",
                    runtime="native.payload.pickup",
                    authority="actuate",
                ),
                _action(
                    "delivery.scan-code",
                    delivery,
                    "扫描交接码",
                    "扫描并验证 QR、条码或 RFID 交接凭证。",
                    success=["code captured", "identity accepted"],
                    fallbacks=["hold", "return"],
                    simulator="sim.payload.scan-code",
                    runtime="native.payload.scan-code",
                    input_schema={
                        "type": "object",
                        "properties": {"expected_format": {"type": "string"}},
                        "additionalProperties": False,
                    },
                ),
                _action(
                    "delivery.verify-recipient",
                    delivery,
                    "核验接收方",
                    "根据任务合同验证接收方身份。",
                    success=["recipient identity accepted"],
                    fallbacks=["hold", "return"],
                    simulator="sim.payload.verify-recipient",
                    runtime="native.payload.verify-recipient",
                ),
                _action(
                    "delivery.release-payload",
                    delivery,
                    "释放载荷",
                    "在接收方和放置区域均确认后释放载荷。",
                    payload=True,
                    success=["payload released", "release area clear"],
                    fallbacks=["hold", "return", "abort"],
                    simulator="sim.payload.release",
                    runtime="native.payload.release",
                    authority="actuate",
                ),
            ],
        ),
        _definition(
            plugin_id="actions.infrastructure-inspection",
            name="设施巡检动作",
            description="提供稳定视点、RGB、热成像和缺陷复核动作。",
            domain_id=inspection,
            order=30,
            actions=[
                _action(
                    "inspection.capture-rgb",
                    inspection,
                    "采集可见光图像",
                    "在稳定视点采集带位姿和时间戳的 RGB 证据。",
                    success=["image captured", "pose bound", "timestamp bound"],
                    fallbacks=["hold", "continue", "return"],
                    simulator="sim.sensor.capture-rgb",
                    runtime="native.sensor.capture-rgb",
                ),
                _action(
                    "inspection.capture-thermal",
                    inspection,
                    "采集热成像",
                    "采集带温度标定和位姿绑定的热成像证据。",
                    success=["thermal frame captured", "calibration valid"],
                    fallbacks=["hold", "continue", "return"],
                    simulator="sim.sensor.capture-thermal",
                    runtime="native.sensor.capture-thermal",
                ),
                _action(
                    "inspection.facade-pass",
                    inspection,
                    "立面巡检航段",
                    "保持安全净空和成像重叠率完成立面航段。",
                    movement=True,
                    success=["coverage complete", "clearance maintained"],
                    fallbacks=["hold", "return", "land"],
                    simulator="sim.inspection.facade-pass",
                    runtime="native.inspection.facade-pass",
                    authority="control",
                ),
                _action(
                    "inspection.confirm-defect",
                    inspection,
                    "缺陷复核",
                    "从第二视角重新采集疑似缺陷并绑定证据。",
                    success=["second viewpoint captured", "defect record bound"],
                    fallbacks=["hold", "continue", "return"],
                    simulator="sim.inspection.confirm-defect",
                    runtime="native.inspection.confirm-defect",
                ),
            ],
        ),
        _definition(
            plugin_id="actions.area-survey",
            name="区域测绘动作",
            description="提供网格影像、激光扫描和采样点任务。",
            domain_id=survey,
            order=40,
            actions=[
                _action(
                    "survey.grid-capture",
                    survey,
                    "网格影像采集",
                    "按照重叠率和地面分辨率要求执行网格覆盖。",
                    movement=True,
                    success=["coverage target met", "image overlap met"],
                    fallbacks=["hold", "return", "land"],
                    simulator="sim.survey.grid-capture",
                    runtime="native.survey.grid-capture",
                    authority="control",
                ),
                _action(
                    "survey.lidar-scan",
                    survey,
                    "激光点云扫描",
                    "采集带时间同步和位姿绑定的点云。",
                    success=["point cloud captured", "time sync valid"],
                    fallbacks=["hold", "continue", "return"],
                    simulator="sim.sensor.lidar-scan",
                    runtime="native.sensor.lidar-scan",
                ),
                _action(
                    "survey.waypoint-sample",
                    survey,
                    "航点采样",
                    "在合同指定采样点完成传感器读数采集。",
                    success=["sample captured", "location bound"],
                    fallbacks=["hold", "continue", "return"],
                    simulator="sim.survey.waypoint-sample",
                    runtime="native.survey.waypoint-sample",
                ),
            ],
        ),
        _definition(
            plugin_id="actions.emergency-response",
            name="应急响应动作",
            description="提供扇区搜索、医疗包投放和信标动作，安全授权保持核心所有。",
            domain_id=emergency,
            order=50,
            actions=[
                _action(
                    "emergency.search-sector",
                    emergency,
                    "扇区搜索",
                    "在给定时间和能源预算内搜索指定区域。",
                    movement=True,
                    success=["sector coverage complete", "detections recorded"],
                    fallbacks=["hold", "return", "land"],
                    simulator="sim.emergency.search-sector",
                    runtime="native.emergency.search-sector",
                    authority="control",
                ),
                _action(
                    "emergency.drop-kit",
                    emergency,
                    "投放应急物资",
                    "确认投放区域无人后释放医疗或通信物资。",
                    payload=True,
                    success=["drop zone clear", "payload released", "release verified"],
                    fallbacks=["hold", "return", "abort"],
                    simulator="sim.payload.drop-kit",
                    runtime="native.payload.drop-kit",
                    authority="actuate",
                ),
                _action(
                    "emergency.signal-beacon",
                    emergency,
                    "发送定位信标",
                    "在任务目标附近发送带位置的应急信标。",
                    success=["beacon transmitted", "location acknowledged"],
                    fallbacks=["continue", "return"],
                    simulator="sim.communication.signal-beacon",
                    runtime="native.communication.signal-beacon",
                ),
            ],
        ),
        _definition(
            plugin_id="actions.facility-maintenance",
            name="设施维护动作",
            description="提供连接处复核、净空测量和材料状态检查动作。",
            domain_id=maintenance,
            order=60,
            actions=[
                _action(
                    "maintenance.inspect-joint",
                    maintenance,
                    "检查连接处",
                    "从多个角度检查楼体、道路或设备连接处的空隙与穿插。",
                    success=["multi-angle evidence", "joint classification recorded"],
                    fallbacks=["hold", "continue", "return"],
                    simulator="sim.maintenance.inspect-joint",
                    runtime="native.maintenance.inspect-joint",
                ),
                _action(
                    "maintenance.measure-clearance",
                    maintenance,
                    "测量净空",
                    "测量目标连接处或通行区域的最小净空。",
                    success=["clearance measured", "measurement pose bound"],
                    fallbacks=["hold", "continue", "return"],
                    simulator="sim.maintenance.measure-clearance",
                    runtime="native.maintenance.measure-clearance",
                ),
            ],
        ),
    ]
