function assert(value: unknown, message: string): asserts value {
  if (!value) throw new Error(message);
}

const adminMigrationUrl = new URL(
  "../../migrations/20260803010000_create_admin_console.sql",
  import.meta.url,
);
const eventMigrationUrl = new URL(
  "../../migrations/20260803020000_create_product_events.sql",
  import.meta.url,
);
const userLifecycleMigrationUrl = new URL(
  "../../migrations/20260812020000_admin_user_lifecycle.sql",
  import.meta.url,
);

async function migrations(): Promise<{ admin: string; events: string; userLifecycle: string }> {
  const [admin, events, userLifecycle] = await Promise.all([
    Deno.readTextFile(adminMigrationUrl),
    Deno.readTextFile(eventMigrationUrl),
    Deno.readTextFile(userLifecycleMigrationUrl),
  ]);
  return { admin, events, userLifecycle };
}

Deno.test("admin tables and RPCs are service-role only and audit is append-only", async () => {
  const { admin } = await migrations();
  for (
    const table of [
      "app_admins",
      "admin_audit_log",
      "model_provider_policies",
    ]
  ) {
    assert(
      admin.includes(`alter table public.${table} enable row level security`),
      `${table} must enable RLS`,
    );
    assert(
      admin.includes(
        `revoke all on table public.${table} from anon, authenticated`,
      ),
      `${table} must deny direct browser roles`,
    );
  }
  assert(
    admin.includes("before update or delete on public.admin_audit_log"),
    "audit evidence must be append-only",
  );
  assert(
    admin.includes(
      "grant execute on function public.admin_bootstrap_owner(uuid) to service_role",
    ),
    "owner bootstrap must remain service-role only",
  );
  assert(
    !admin.includes(
      "grant execute on function public.admin_bootstrap_owner(uuid) to authenticated",
    ),
    "authenticated users must never call owner bootstrap directly",
  );
});

Deno.test("model policy uses CAS, append-only audit, and provider enforcement", async () => {
  const { admin } = await migrations();
  assert(
    admin.includes(
      "where provider = p_provider and version = p_expected_version",
    ),
    "model updates must use optimistic concurrency",
  );
  assert(
    admin.includes("MODEL_POLICY_VERSION_CONFLICT"),
    "version conflicts must remain explicit",
  );
  assert(
    admin.includes("'model_policy.updated'"),
    "model policy changes must append audit evidence",
  );
  assert(
    admin.includes("MODEL_PROVIDER_DISABLED"),
    "disabled providers must fail closed",
  );
  assert(
    admin.includes("grant_row.provider <> new.provider") &&
      admin.includes("grant_row.scope <> new.purpose"),
    "old or mismatched grants must not bypass the current provider policy",
  );
  assert(
    admin.includes("p_provider text") &&
      admin.includes("p_provider not in ('openai', 'deepseek', 'qwen')"),
    "grant issuance must bind an allowlisted provider",
  );
});

Deno.test("community moderation is soft-delete plus atomic audit", async () => {
  const { admin } = await migrations();
  assert(
    admin.includes("add column if not exists hidden_at timestamptz") &&
      admin.includes("using (hidden_at is null)"),
    "public community reads must hide moderated topics",
  );
  const removeFunction = admin.slice(
    admin.indexOf(
      "create or replace function public.admin_remove_community_topic",
    ),
    admin.indexOf("alter table public.model_gateway_grants"),
  );
  assert(
    removeFunction.includes("update public.community_topics") &&
      !removeFunction.includes("delete from public.community_topics"),
    "moderation must never physically delete the topic",
  );
  assert(
    removeFunction.includes("insert into public.admin_audit_log"),
    "soft removal and audit must share one database transaction",
  );
  assert(
    removeFunction.includes(
      "char_length(btrim(coalesce(p_reason, ''))) not between 8 and 500",
    ),
    "removal reasons must be bounded in the database",
  );
});

Deno.test("product events derive server receipt time and deny direct browser access", async () => {
  const { events } = await migrations();
  assert(
    events.includes("primary key (user_id, event_id)"),
    "idempotency must be isolated per verified user",
  );
  assert(
    events.includes("received_at timestamptz not null default now()"),
    "received_at must be generated by the server",
  );
  assert(
    events.includes(
      "alter table public.product_events enable row level security",
    ) &&
      events.includes(
        "revoke all on table public.product_events from anon, authenticated",
      ),
    "browser roles must not insert or select analytics rows directly",
  );
  assert(
    events.includes("grant execute on function public.record_product_event(") &&
      events.includes(") to service_role"),
    "only the trusted function may execute event storage",
  );
  assert(
    !events.includes(") to authenticated") && !events.includes(") to anon"),
    "event storage RPC must not be callable by browser roles",
  );
  for (
    const forbidden of [
      "password",
      "encrypted_password",
      "api_key",
      "refresh_token",
    ]
  ) {
    assert(
      !events.toLocaleLowerCase("en-US").includes(forbidden),
      `analytics migration must not mention ${forbidden}`,
    );
  }
});

Deno.test("owner user deletion is atomic, audited, and retention aware", async () => {
  const { userLifecycle } = await migrations();
  const deletion = userLifecycle.slice(
    userLifecycle.indexOf("create or replace function public.admin_delete_user"),
    userLifecycle.indexOf("notify pgrst"),
  );
  assert(
    userLifecycle.includes("'users.delete'") &&
      userLifecycle.includes("role = 'owner'"),
    "only the owner role should receive user deletion authority",
  );
  assert(
    deletion.includes("insert into public.admin_audit_log") &&
      deletion.includes("delete from auth.users"),
    "audit and account deletion must share one database transaction",
  );
  assert(
    deletion.indexOf("insert into public.admin_audit_log") <
      deletion.indexOf("delete from auth.users"),
    "the immutable audit receipt must be authorized before deletion",
  );
  assert(
    deletion.includes("ADMIN_USER_DELETE_RETENTION_REQUIRED") &&
      deletion.includes("public.payment_orders") &&
      deletion.includes("public.organization_audit_log"),
    "protected history must fail closed instead of being erased",
  );
  assert(
    !deletion.includes("target_email") &&
      !deletion.includes("select email") &&
      deletion.includes("p_target_user_id::text"),
    "the audit may retain the account UUID but must not copy the user's email",
  );
  assert(
    userLifecycle.includes(
      "grant execute on function public.admin_delete_user(uuid, uuid, text)",
    ) && !userLifecycle.includes("to authenticated"),
    "only the service role may invoke the deletion RPC",
  );
});
